---
id: wicked
name: Wicked
full: Wiki application
description: Wicked is a wiki application for Horde.
list: horde
type: application
homepage: https://www.horde.org/apps/wicked
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 2.0.9
  api: 2.0.0
state:
  release: stable
  api: stable
license:
  identifier: GPL-2.0
  uri: http://www.horde.org/licenses/gpl
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/horde: ^5
      pear.horde.org/Horde_Auth: ^2
      pear.horde.org/Horde_Autoloader: ^2
      pear.horde.org/Horde_Core: ^2
      pear.horde.org/Horde_Db: ^2
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Form: ^2
      pear.horde.org/Horde_Http: ^2
      pear.horde.org/Horde_Lock: ^2
      pear.horde.org/Horde_Mail: ^2
      pear.horde.org/Horde_Mime: ^2
      pear.horde.org/Horde_Mime_Viewer: ^2
      pear.horde.org/Horde_Notification: ^2
      pear.horde.org/Horde_Perms: ^2
      pear.horde.org/Horde_Prefs: ^2
      pear.horde.org/Horde_Rpc: ^2
      pear.horde.org/Horde_Text_Diff: ^2
      pear.horde.org/Horde_Url: ^2
      pear.horde.org/Horde_Util: ^2
      pear.horde.org/Horde_Vfs: ^2
    ext:
      gettext: '*'
  optional:
    pear:
      pear.php.net/Text_Figlet: '*'
